#!/usr/bin/env python3
"""Generate lib/src/ohos_icons.dart from tool/data/name_map_new.json.

Produces:
  * `OhosIcons` - one `IconData` constant per HarmonyOS Symbol
  * `OhosIconMeta` - rich metadata (Chinese label, category, module, version)
  * `OhosIcons.info` - name -> metadata lookup

Usage:
  python3 tool/generate_icons.py \
      --meta tool/data/name_map_new.json \
      --out lib/src/ohos_icons.dart
"""

from __future__ import annotations

import argparse
import json
import pathlib

DART_ESCAPES = {
    "\\": "\\\\",
    "'": "\\'",
    "$": "\\$",
    "\n": "\\n",
    "\r": "\\r",
    "\t": "\\t",
}


def dart_str(value: str) -> str:
    return "'" + "".join(DART_ESCAPES.get(c, c) for c in value) + "'"


def dart_doc(*lines: str, indent: str = "  ") -> str:
    return "\n".join(f"{indent}/// {line}" for line in lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--meta", default="tool/data/name_map_new.json")
    parser.add_argument("--out", default="lib/src/ohos_icons.dart")
    args = parser.parse_args()

    with open(args.meta, encoding="utf-8") as fh:
        raw = json.load(fh)

    version = raw.get("version", "?")
    by_name: dict[str, dict] = {}
    for icons in raw["data"].values():
        for icon in icons:
            by_name.setdefault(icon["name"], icon)

    icons = sorted(by_name.values(), key=lambda i: i["name"])
    total = len(icons)

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("// GENERATED CODE - DO NOT MODIFY BY HAND")
    lines.append("// ignore_for_file: constant_identifier_names, non_constant_identifier_names")
    lines.append("// Generated by tool/generate_icons.py from tool/data/name_map_new.json")
    lines.append(f"// HarmonyOS Symbol version: {version}, {total} icons.")
    lines.append("// Source: https://developer.huawei.com/consumer/cn/design/harmonyos-symbol/")
    lines.append("")
    lines.append("import 'package:flutter/widgets.dart';")
    lines.append("")
    lines.append("/// Metadata for a single HarmonyOS Symbol.")
    lines.append("class OhosIconMeta {")
    lines.append("  const OhosIconMeta({")
    lines.append("    required this.name,")
    lines.append("    required this.label,")
    lines.append("    required this.module,")
    lines.append("    required this.categories,")
    lines.append("    required this.supportVersion,")
    lines.append("    required this.codepoint,")
    lines.append("    this.mirrorCodepoint,")
    lines.append("  });")
    lines.append("")
    lines.append("  /// English identifier, e.g. `airplane_fill`.")
    lines.append("  final String name;")
    lines.append("")
    lines.append("  /// Chinese name, e.g. `飞行模式`.")
    lines.append("  final String label;")
    lines.append("")
    lines.append("  /// Module the symbol belongs to, e.g. `状态栏`.")
    lines.append("  final String module;")
    lines.append("")
    lines.append("  /// Categories the symbol appears in on the official site.")
    lines.append("  final List<String> categories;")
    lines.append("")
    lines.append("  /// Minimum HarmonyOS version, e.g. `HarmonyOS 5.0+`.")
    lines.append("  final String supportVersion;")
    lines.append("")
    lines.append("  /// Codepoint of the symbol in the `HMSymbol` font.")
    lines.append("  final int codepoint;")
    lines.append("")
    lines.append("  /// Optional codepoint of the RTL mirror variant.")
    lines.append("  final int? mirrorCodepoint;")
    lines.append("")
    lines.append("  /// The [IconData] that renders this symbol.")
    lines.append("  IconData get icon => IconData(")
    lines.append("    codepoint,")
    lines.append("    fontFamily: OhosIcons.fontFamily,")
    lines.append("    fontPackage: OhosIcons.fontPackage,")
    lines.append("  );")
    lines.append("")
    lines.append("  /// The [IconData] of the RTL mirror variant, when [mirrorCodepoint] is set.")
    lines.append("  IconData? get mirrorIcon => mirrorCodepoint == null")
    lines.append("      ? null")
    lines.append("      : IconData(")
    lines.append("          mirrorCodepoint!,")
    lines.append("          fontFamily: OhosIcons.fontFamily,")
    lines.append("          fontPackage: OhosIcons.fontPackage,")
    lines.append("        );")
    lines.append("}")
    lines.append("")
    lines.append("/// HarmonyOS Symbol icon font rendered as Flutter [IconData] constants.")
    lines.append("///")
    lines.append("/// Mirrors the official `HM Symbol` icon font shipped with HarmonyOS.")
    lines.append("class OhosIcons {")
    lines.append("  OhosIcons._();")
    lines.append("")
    lines.append("  /// Font family name, must match the `family` in pubspec.yaml.")
    lines.append("  static const String fontFamily = 'HMSymbol';")
    lines.append("")
    lines.append("  /// Package name, used to resolve the font asset from other packages.")
    lines.append("  static const String fontPackage = 'ohos_icons';")
    lines.append("")
    lines.append("  /// Version of the source icon metadata, e.g. `2.3`.")
    lines.append(f"  static const String version = '{version}';")
    lines.append("")
    lines.append("  /// Number of unique symbols in this package.")
    lines.append(f"  static const int count = {total};")
    lines.append("")
    lines.append("  /// English names of every symbol, sorted alphabetically.")
    names = sorted(by_name)
    per_line = 8
    lines.append("  static const List<String> names = [")
    for i in range(0, len(names), per_line):
        chunk = ", ".join("'" + n.replace("\\", "\\\\").replace("'", "\\'") + "'" for n in names[i:i + per_line])
        suffix = "," if i + per_line < len(names) else ""
        lines.append(f"    {chunk}{suffix}")
    lines.append("  ];")
    lines.append("")
    lines.append("  /// All icon metadata.")
    lines.append("  static Iterable<OhosIconMeta> get values => info.values;")
    lines.append("")
    lines.append("  /// All category names, sorted.")
    lines.append("  static List<String> get categories =>")
    lines.append("      (info.values.expand((m) => m.categories).toSet().toList()..sort());")
    lines.append("")

    for icon in icons:
        name = icon["name"]
        label = icon.get("name_cn", "")
        support = icon.get("support_version", "")
        doc = f"/// {label} · {name}" if label else f"/// {name}"
        if support:
            doc += f" · {support}"
        lines.append(doc)
        lines.append(
            f"  static const IconData {name} = IconData("
            f"0x{int(icon['unicode'], 16):X}, fontFamily: fontFamily, "
            "fontPackage: fontPackage);"
        )
        lines.append("")

    lines.append("  /// All icon metadata keyed by symbol name.")
    lines.append("  static const Map<String, OhosIconMeta> info = {")
    for icon in icons:
        name = icon["name"]
        categories = ", ".join(dart_str(c) for c in icon.get("category", []))
        mirror = icon.get("mirror_unicode")
        mirror_src = f"mirrorCodepoint: 0x{int(mirror, 16):X}," if mirror else ""
        lines.append(f"    {dart_str(name)}: OhosIconMeta(")
        lines.append(f"      name: {dart_str(name)},")
        lines.append(f"      label: {dart_str(icon.get('name_cn', ''))},")
        lines.append(f"      module: {dart_str(icon.get('module', ''))},")
        lines.append(f"      categories: [{categories}],")
        lines.append(f"      supportVersion: {dart_str(icon.get('support_version', ''))},")
        lines.append(f"      codepoint: 0x{int(icon['unicode'], 16):X},")
        if mirror_src:
            lines.append(f"      {mirror_src}")
        lines.append("    ),")
    lines.append("  };")
    lines.append("")
    lines.append("  /// Looks up the [IconData] for a symbol by its English name.")
    lines.append("  static IconData fromName(String name) {")
    lines.append("    return info[name]?.icon ??")
    lines.append("        (throw ArgumentError.value(name, 'name', 'unknown symbol'));")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({total} icons)")


if __name__ == "__main__":
    main()
